approvedGitRepositories:
  - "**"

catalog:
  es-toolkit: 1.49.0
  typescript: 6.0.3
  vite-plus: 0.2.5
  devframe: 0.9.5

catalogs:
  rolldown:
    "@rollipop/rolldown": 1.0.25

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@rollipop/*"
  - es-toolkit
  - typescript
  - "@typescript/*"
  - vite-plus
  - "@react-native/*"
  - "@oxc-project/*"
  - "@swc/*"
  - fastify
  - fastify-*
  - "@fastify/*"
  - rolldown-analyzer
  - source-map

npmPublishAccess: public

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAlwaysAuth: true
