import { DEFAULT_HOST, DEFAULT_PORT } from '../../../server';
import type { CommandAction } from '../../types';

export type AgentCommandOptions = Record<string, never>;

const defaultBaseUrl = `http://${DEFAULT_HOST}:${DEFAULT_PORT}`;

export function getAgentGuide(baseUrl = defaultBaseUrl): string {
  return [
    'Rollipop Agent Guide',
    '',
    'Rollipop exposes build events and client logs through SSE, with optional MCP tooling.',
    'Keep the dev server running, then connect your agent to one of these endpoints.',
    '',
    'Start the dev server:',
    '',
    '  rollipop start --mcp --reset-cache',
    '',
    'Default endpoints:',
    '',
    `  SSE events:       ${baseUrl}/sse/events`,
    `  SSE client logs:  ${baseUrl}/sse/client-logs`,
    `  MCP server:       ${baseUrl}/mcp (requires start --mcp)`,
    '',
    'If you start Rollipop with custom --host, --port, or --https options,',
    'adjust these URLs to match the running dev server.',
    '',
    'SSE usage:',
    '',
    `  curl -N ${baseUrl}/sse/events`,
    `  curl -N ${baseUrl}/sse/client-logs`,
    '',
    '  Event format:',
    '    event: <event_type>',
    '    data: <json_payload>',
    '    bundler-scoped events include bundlerId',
    '',
    '  Useful event types:',
    '    bundle_build_started, bundle_build_done, bundle_build_failed',
    '    watch_change, device_connected, device_disconnected',
    '    server_ready, cache_reset',
    '    client_log is streamed separately from /sse/client-logs',
    '',
    '  bundle_build_done includes bundleFilePath for the file-system bundle.',
    '  Rollipop serves that file when it has been edited after the build,',
    '  which lets agents inspect or patch the final bundle for debugging.',
    '',
    'MCP setup:',
    '',
    '  Add this to your project .mcp.json:',
    '',
    '    {',
    '      "mcpServers": {',
    '        "rollipop": {',
    '          "type": "http",',
    `          "url": "${baseUrl}/mcp"`,
    '        }',
    '      }',
    '    }',
    '',
    '  Tool discovery:',
    '    MCP clients discover supported tools by calling tools/list.',
    '    The response includes tool names, descriptions, and input schemas.',
    '    For Streamable HTTP, initialize first, then call tools/list with',
    '    the returned mcp-session-id header.',
    '',
    'External debugging:',
    '',
    '  CDP debugging, runtime evaluation, runtime errors, network inspection,',
    '  and profiling can be handled by agent-cdp:',
    '    https://github.com/callstackincubator/agent-cdp',
    '',
    '  React component tree inspection and React DevTools profiling can be',
    '  handled by agent-react-devtools:',
    '    https://github.com/callstackincubator/agent-react-devtools',
    '',
    'Agent workflow:',
    '',
    '  1. Run rollipop start and keep it running; add --mcp when using MCP tools.',
    '  2. Use get_build_events or /sse/events before and after edits.',
    '  3. Wait for bundle_build_done or bundle_build_failed.',
    '  4. Use get_bundler_status when you need the latest state for a known bundlerId.',
    '  5. Use clear_build_* and clear_console_logs before focused diagnostics when old buffered data may be noisy.',
    '  6. Use bundleFilePath from bundle_build_done when bundle-level debugging is needed.',
    '  7. If the build fails, inspect the error payload, fix the code, and repeat.',
    '  8. Use reset_cache when stale cache is suspected.',
  ].join('\n');
}

export const action: CommandAction<AgentCommandOptions> = async () => {
  console.log(getAgentGuide());
};
