name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  default-workflow:
    name: ${{ matrix.os == 'ubuntu-latest' && 'Default Workflow' || 'macOS Workflow' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Tools
        uses: jdx/mise-action@v3

      - name: Setup Node
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build:all

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck:all

      - name: Test
        run: yarn test:all
